export const translations = {
  en: {
    titleDev: "Front End Developer" ,
    heroRole: "Frontend Developer & Software Engineer",
    intro: "I'm Ahmani Elmokhtar, a Frontend Developer and Software Engineer focused on building modern, production-ready web applications with React, Next.js and TypeScript.",
    build: 'Build accessible, pixel-perfect digital experiences for the web. ',
    technologiesLabel: "Technologies",
    openMenu: "Open navigation menu",
    closeMenu: "Close navigation menu",
    switchToEnglish: "Switch to English",
    switchToFrench: "Switch to French",
    linkedinProfile: "LinkedIn profile",
    githubProfile: "GitHub profile",
    experienceTitle: "Experience",
    experience1: {
      title: "Frontend Developer",
      company: "Elavi.ma",
      duration: "2025 — Present",
      description: [
        "Creation and integration of HTML5, CSS3, and JavaScript",
        "Responsive design implementation",
        "Technical site auditing",
        "Email integration",
        "Development of components using React/Next.js",
        "Source code analysis and auditing",
        "Compliance verification with W3C standards",
        "Page integration in Drupal 7"
      ],
    },
    experience2: {
      title: "Frontend Developer",
      company: "Freelance",
      duration: "2021 — January",
      description: [
        "Creation and integration of HTML5, CSS3, and JavaScript ",
        "Responsive design implementation",
        "Technical site auditing",
        "Email integration",
        "Development of components using React/Next.js",
        "Source code analysis and auditing",
        "Compliance verification with W3C standards",
        "Page integration in Drupal 7"
      ],
    },
    aboutTitle: "About Me",
    aboutMe: "As a software development graduate, I bring energy, precision, and adaptability to every project I take on. With a strong passion for front-end development, particularly with React.js, I am always striving to enhance user experiences through clean, efficient code. My goal is to help drive the success of your business by delivering innovative solutions. I look forward to applying my skills to your team and embracing new challenges along the way.",
    projectsTitle: "Projects",
    printPilotSubtitle: "Online Print Editor",
    printPilotShort: "Browser-based print editor for importing, editing, previewing and exporting production-ready PDF artwork with bleed and trim handling.",
    printPilotOverview: "PrintPilot is a production web application embedded in Batteria's e-commerce printing workflow. It combines an interactive editor with PDF and image handling, print dimensions and a print-ready export flow.",
    printPilotChallenge: "Professional print documents require physical dimensions, bleed, trim areas, imported PDFs and high-resolution output while the interface still needs to feel usable in a browser.",
    printPilotContribution: ["Built and maintained core frontend functionality", "Implemented PDF and image import workflows", "Worked on canvas-based document manipulation and print previews", "Implemented bleed, trim and safe-area handling", "Integrated the editor with the surrounding e-commerce workflow", "Worked on configuration loading and save integrations", "Debugged rendering, scaling and PDF compatibility issues"],
    printPilotHighlights: ["Hybrid PDF rendering with vector placement where possible and raster fallbacks when required", "Canvas editing for images, text, shapes and PDF content with transformed element properties", "Conversions between pixels, millimeters and PDF coordinates for print dimensions", "PDF page-box handling for MediaBox, CropBox and TrimBox", "High-resolution PNG previews, thumbnails and front/back visualization", "Pixel-ratio limits to balance print quality with browser memory"],
    printPilotArchitecture: [{ name: "Import", description: "Loads documents, renders pages and creates thumbnails." }, { name: "Editor state", description: "Coordinates document elements, dimensions and transformations." }, { name: "Preview", description: "Generates visual front/back representations before production." }, { name: "Hybrid PDF export", description: "Combines vector content with raster fallbacks for reliable output." }],
    printPilotLabels: { details: "View project details", overview: "Overview", challenge: "The challenge", contribution: "My contribution", highlights: "Technical highlights", architecture: "Architecture", technologies: "Technologies" },
    batteriaSubtitle: "B2B Web-to-Print E-commerce Platform",
    batteriaShort: "Modernized B2B printing platform connecting configurable products, customer artwork and e-commerce workflows through a Next.js and React.js frontend.",
    batteriaOverview: "Batteria.be is a B2B web-to-print e-commerce platform whose customer-facing experience was migrated from a legacy Drupal 7 frontend to a modern Next.js and React.js application. The new frontend preserves existing product data and business logic through API integrations.",
    batteriaChallenge: "The migration needed to preserve existing backend compatibility, product data and business rules while rebuilding pages and complex e-commerce workflows as reusable, responsive React components.",
    batteriaContribution: ["Migrated the legacy Drupal 7 frontend to Next.js and React.js", "Rebuilt existing pages and interfaces as reusable React components", "Integrated the new frontend with existing backend APIs", "Preserved existing product data and business rules during the migration", "Developed responsive and reusable UI components", "Worked on configurable product and pricing workflows", "Implemented cart and checkout interfaces", "Worked on customer account flows", "Integrated PrintPilot into the artwork preparation workflow", "Improved frontend maintainability, performance and user experience"],
    batteriaHighlights: ["Progressive frontend migration from Drupal 7 while maintaining existing backend compatibility", "Reusable React interfaces for product browsing, configurable print products and pricing", "Connected customer journeys across catalogue, artwork preparation, cart and checkout", "REST API integrations preserving existing product data and business rules", "Responsive, multilingual e-commerce experiences built for maintainability"],
    batteriaArchitecture: [{ name: "Drupal 7 frontend", description: "Legacy customer-facing pages progressively replaced during the migration." }, { name: "Next.js / React.js", description: "Reusable responsive interfaces for the modernized e-commerce experience." }, { name: "Backend APIs", description: "Existing product data and business logic connected to the new frontend." }, { name: "PrintPilot", description: "Artwork preparation integrated into the product and checkout workflow." }],
    batteriaLabels: { details: "View project details", overview: "Overview", challenge: "The challenge", contribution: "My contribution", highlights: "Technical highlights", architecture: "Architecture", technologies: "Technologies" },
    flyerbeDescription: "An online printing e-commerce platform. Creation and integration of websites using HTML5, CSS3, JQ, and PHP5 (Drupal 7).",
    flyerfrDescription: "An online printing e-commerce platform specializing in printing services. Development and maintenance of key frontend components to improve accessibility and user experience.",
    printPilotDescription: "Browser-based print editor integrated into Batteria's e-commerce workflow. Built and maintained core frontend features for uploading and processing PDF/image files, managing print layouts, previews and print-ready artwork. Worked on the integration between the e-commerce platform and the editor, with a strong focus on usability, responsive interfaces and reliable handling of complex print configurations.",
    mercuryDescription: "Development and maintenance of a custom website for Mercury Flooring, a leading provider of flooring solutions.",
  },
  fr: {
    titleDev: "Développeur Frontend",
    heroRole: "Développeur Frontend et Ingénieur Logiciel",
    intro: "Je suis Ahmani Elmokhtar, développeur frontend et ingénieur logiciel spécialisé dans la création d'applications web modernes et prêtes pour la production avec React, Next.js et TypeScript.",
    build: 'Construire des expériences numériques accessibles et fidèles au pixel pour le web. ',
    technologiesLabel: "Technologies",
    openMenu: "Ouvrir le menu de navigation",
    closeMenu: "Fermer le menu de navigation",
    switchToEnglish: "Passer en anglais",
    switchToFrench: "Passer en français",
    linkedinProfile: "Profil LinkedIn",
    githubProfile: "Profil GitHub",
    experienceTitle: "Expérience",
    experience1: {
      title: "Développeur Frontend",
      company: "Elavi.ma",
      duration: "2025 — Présent",
      description: [
        "Création et intégration de HTML5, CSS3, et JavaScript",
        "Mise en œuvre de design responsive",
        "Audit technique du site",
        "Intégration des e-mails",
        "Développement de composants avec React/Next.js",
        "Analyse et audit du code source",
        "Vérification de la conformité aux normes W3C",
        "Intégration des pages dans Drupal 7"
      ],
    },
    experience2: {
      title: "Développeur Frontend",
      company: "Freelance",
      duration: "2021 — Janvier",
      description: [
        "Création et intégration de HTML5, CSS3, et JavaScript",
        "Mise en œuvre de design responsive",
        "Audit technique du site",
        "Intégration des e-mails",
        "Développement de composants avec React/Next.js",
        "Analyse et audit du code source",
        "Vérification de la conformité aux normes W3C",
        "Intégration des pages dans Drupal 7"
      ],
    },
    aboutTitle: "A propos",
    aboutMe: "En tant que diplômé en développement logiciel, j'apporte de l'énergie, de la précision et de l'adaptabilité à chaque projet que je prends en charge. Avec une forte passion pour le développement front-end, en particulier avec React.js, je m'efforce toujours d'améliorer l'expérience utilisateur grâce à un code propre et efficace. Mon objectif est de contribuer au succès de votre entreprise en offrant des solutions innovantes. J'ai hâte de mettre mes compétences au service de votre équipe et de relever de nouveaux défis.",
    projectsTitle: "Projets",
    printPilotSubtitle: "Éditeur d'impression en ligne",
    printPilotShort: "Éditeur d'impression en ligne pour importer, modifier, prévisualiser et exporter des fichiers PDF prêts pour la production, avec gestion du fond perdu et du format fini.",
    printPilotOverview: "PrintPilot est une application web de production intégrée au parcours e-commerce d'impression de Batteria. Elle associe un éditeur interactif à la gestion des PDF et des images, aux dimensions d'impression et à un flux d'export prêt pour la production.",
    printPilotChallenge: "Les documents d'impression professionnels exigent des dimensions physiques, du fond perdu, des zones de coupe, des PDF importés et un rendu haute résolution, tout en conservant une interface utilisable dans un navigateur.",
    printPilotContribution: ["Développement et maintenance des fonctionnalités frontend principales", "Implémentation des flux d'import PDF et image", "Travail sur la manipulation des documents sur canvas et les prévisualisations", "Implémentation de la gestion du fond perdu, du format fini et de la zone de sécurité", "Intégration de l'éditeur au parcours e-commerce", "Travail sur le chargement et la sauvegarde des configurations", "Correction de problèmes de rendu, de mise à l'échelle et de compatibilité PDF"],
    printPilotHighlights: ["Rendu PDF hybride avec placement vectoriel lorsque possible et solutions raster de secours", "Édition sur canvas d'images, textes, formes et contenus PDF avec transformations", "Conversions entre pixels, millimètres et coordonnées PDF pour les dimensions d'impression", "Gestion des zones PDF MediaBox, CropBox et TrimBox", "Prévisualisations PNG haute résolution, miniatures et visualisation recto/verso", "Limitation du pixel ratio pour équilibrer qualité d'impression et mémoire du navigateur"],
    printPilotArchitecture: [{ name: "Import", description: "Charge les documents, rend les pages et crée les miniatures." }, { name: "État de l'éditeur", description: "Coordonne les éléments, dimensions et transformations." }, { name: "Prévisualisation", description: "Génère les représentations recto/verso avant production." }, { name: "Export PDF hybride", description: "Combine contenu vectoriel et solutions raster de secours." }],
    printPilotLabels: { details: "Voir les détails du projet", overview: "Présentation", challenge: "Le défi", contribution: "Ma contribution", highlights: "Points techniques", architecture: "Architecture", technologies: "Technologies" },
    batteriaSubtitle: "Plateforme e-commerce B2B Web-to-Print",
    batteriaShort: "Modernisation d'une plateforme d'impression B2B reliant produits configurables, fichiers clients et parcours e-commerce avec un frontend Next.js et React.js.",
    batteriaOverview: "Batteria.be est une plateforme e-commerce B2B Web-to-Print dont l'expérience client a été migrée d'un frontend Drupal 7 historique vers une application moderne Next.js et React.js. Le nouveau frontend préserve les données produits et la logique métier grâce aux intégrations API.",
    batteriaChallenge: "La migration devait préserver la compatibilité avec le backend existant, les données produits et les règles métier, tout en reconstruisant les pages et les parcours e-commerce complexes avec des composants React réutilisables et responsives.",
    batteriaContribution: ["Migration du frontend Drupal 7 historique vers Next.js et React.js", "Reconstruction des pages et interfaces avec des composants React réutilisables", "Intégration du nouveau frontend avec les API backend existantes", "Préservation des données produits et des règles métier pendant la migration", "Développement de composants UI responsives et réutilisables", "Travail sur les parcours de produits configurables et de tarification", "Implémentation des interfaces panier et commande", "Travail sur les parcours de compte client", "Intégration de PrintPilot au processus de préparation des fichiers", "Amélioration de la maintenabilité, des performances et de l'expérience utilisateur"],
    batteriaHighlights: ["Migration progressive du frontend Drupal 7 avec maintien de la compatibilité backend", "Interfaces React réutilisables pour le catalogue, les produits configurables et la tarification", "Parcours client reliés entre catalogue, préparation des fichiers, panier et commande", "Intégrations REST API préservant les données produits et les règles métier existantes", "Expériences e-commerce responsives et multilingues conçues pour être maintenables"],
    batteriaArchitecture: [{ name: "Frontend Drupal 7", description: "Pages client historiques progressivement remplacées pendant la migration." }, { name: "Next.js / React.js", description: "Interfaces responsives et réutilisables de l'expérience e-commerce modernisée." }, { name: "API backend", description: "Données produits et logique métier existantes connectées au nouveau frontend." }, { name: "PrintPilot", description: "Préparation des fichiers intégrée au parcours produit et commande." }],
    batteriaLabels: { details: "Voir les détails du projet", overview: "Présentation", challenge: "Le défi", contribution: "Ma contribution", highlights: "Points techniques", architecture: "Architecture", technologies: "Technologies" },
    flyerbeDescription: "Un commerce en ligne (e-Commerce) d'impression. Création et intégration de sites web en utilisant HTML5, CSS3, JQ et PHP5 (Drupal 7).",
    flyerfrDescription: "Un commerce en ligne (e-Commerce) d'impression spécialisé dans les services d'impression. Développement et maintenance des composants clés du frontend pour améliorer l'accessibilité et l'expérience utilisateur.",
    printPilotDescription: "Éditeur d'impression en ligne intégré au parcours e-commerce de Batteria. Développement et maintenance des fonctionnalités frontend principales pour l'import et le traitement de fichiers PDF et image, la gestion des mises en page, des prévisualisations et des fichiers prêts à imprimer. Travail sur l'intégration entre la plateforme e-commerce et l'éditeur, avec un fort accent sur l'ergonomie, les interfaces responsives et la gestion fiable de configurations d'impression complexes.",
    mercuryDescription: "Développement et maintenance d'un site web personnalisé pour Mercury Flooring, un fournisseur leader de solutions de revêtement de sol.",
  },
};

export function getTranslation(lang: string): typeof translations.en {
  if (!(lang in translations)) {
    console.warn(`Unknown language: ${lang}, defaulting to English`);
  }

  return translations[lang as keyof typeof translations] ?? translations.en;
}