import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import Header from "./components/header/header";
import "./globals.css";
import Mode from "./components/mode";


const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} container py-12`}>
        <div className="min-h-screen bg-secondary text-primary dark:bg-primary dark:text-secondary flex md:flex-row flex-col">
          <Header />
          <main className="flex-1">{children}</main>
        </div>
      </body>
      <Mode />

    </html>
  );
}
